---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/docker/ansible"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 99
  - package-ecosystem: docker
    directory: "/docker/kites/net-tests"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 99
  - package-ecosystem: docker
    directory: "/docker/ansible"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 99
...
