---
- name: Update APT cache if needed
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true

- name: Update all APT packages to the latest version
  ansible.builtin.apt:
    upgrade: dist

- name: Copy fix-box.sh script
  ansible.builtin.copy:
    src: /vagrant/scripts/linux/fix-box.sh
    dest: /usr/local/bin/fix-box.sh
    owner: root
    group: root
    mode: '0744'
    remote_src: true

- name: Generate fix-box service configuration file
  ansible.builtin.template:
    backup: false
    dest: /etc/systemd/system/fix-box.service
    group: root
    owner: root
    mode: '0664'
    src: templates/fix-box.service.j2
  notify:
    - systemd_daemon_reload

- name: Enable fix-box service
  ansible.builtin.service:
    name: fix-box
    enabled: true
  notify:
    - systemd_daemon_reload

- name: Add the br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Enable br_netfilter kernel module autoload
  ansible.builtin.template:
    backup: false
    dest: /etc/modules-load.d/br_netfilter.conf
    group: root
    mode: "0755"
    owner: root
    src: templates/br_netfilter.conf.j2
  notify:
    - systemd_modules_load_restart

- name: remove /etc/machine-id
  ansible.builtin.file:
    path: /etc/machine-id
    state: absent

- name: remove /var/lib/dbus/machine-id
  ansible.builtin.file:
    path: /var/lib/dbus/machine-id
    state: absent

- name: Search for DHCP lease files to remove
  ansible.builtin.find:
    paths: /var/lib/dhcp
    patterns: "*"
  register: dhcp_lease_files_to_delete

- name: Delete DHCP lease files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ dhcp_lease_files_to_delete.files }}"

- name: Ensure handlers run before carrying on
  ansible.builtin.meta: flush_handlers

- name: Ensure changes are written on disk
  ansible.builtin.command: >-
    sync
  changed_when: false
...
