{
 "title": "Kubernetes Pod Details",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace:",
    "query": "label_values(kube_namespace_status_phase,namespace)"
   },
   {
    "name": "pod_name",
    "label": "Pod:",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod_name!=\"\", pod_name=~\"[[pod_name]].*\", namespace=~\"[[namespace]].*\"}[5m]) * 100) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name!=\"\", pod_name=~\"[[pod_name]].*\", namespace=~\"[[namespace]].*\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{pod_name=~\"[[pod_name]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{pod_name=~\"[[pod_name]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}