---
name: Build container images

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - ".github/workflows/build-container-images.yaml"
      - "docker/**"
  pull_request:
    paths:
      - ".github/workflows/build-container-images.yaml"
      - "docker/**"

jobs:
  build-container-images:
    env:
      CONTAINER_IMAGE_ID: "netgroup/${{ matrix.container-image-context-directory }}:latest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the OS image builder container image
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: docker/${{ matrix.container-image-context-directory }}
          load: true
          push: false
          tags: "${{ env.CONTAINER_IMAGE_ID }}"
    strategy:
      matrix:
        container-image-context-directory:
          - ansible
          - kites/net-tests
...
