---
name: CI

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Super-Linter
        uses: github/super-linter@v4.9.1
        env:
          DISABLE_ERRORS: false
          ERROR_ON_MISSING_EXEC_BIT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JSCPD_ALL_CODEBASE: true
      - name: Lint InSpec profiles
        run: |
          set -o errexit
          set -o nounset

          scripts/linux/ci/install-linting-tools.sh
          scripts/linux/ci/lint-inspec.sh
...
